quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=secretpassword

quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-service:5432/chatapp

quarkus.hibernate-orm.schema-management.strategy=update

%prod.quarkus.redis.hosts=redis://redis-service:6379

