apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
    - image: identity-service
      context: identity-service
      docker:
        dockerfile: src/main/docker/Dockerfile.jvm
    - image: delivery-service
      context: delivery-service
      docker:
        dockerfile: src/main/docker/Dockerfile.jvm
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    # 1. Skaffold automatically installs the NGINX engine into the cluster
    - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
    # 2. Skaffold applies your database, Java app, and the Ingress rules we just wrote
    - k8s/*.yaml
deploy:
  kubectl: { }
