apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
    - image: identity-service
      context: identity-service
      docker:
        dockerfile: src/main/docker/Dockerfile.jvm
      hooks:
        before:
          - command: ["../mvnw", "package", "-pl", "identity-service", "-am", "-DskipTests"]
            os: [darwin, linux]
          - command: [".\\mvnw.cmd", "package", "-pl", "identity-service", "-am", "-DskipTests"]
            os: [windows]
    - image: delivery-service
      context: delivery-service
      docker:
        dockerfile: src/main/docker/Dockerfile.jvm
      hooks:
        before:
          - command: ["../mvnw", "package", "-pl", "delivery-service", "-am", "-DskipTests"]
            os: [darwin, linux]
          - command: [".\\mvnw.cmd", "package", "-pl", "delivery-service", "-am", "-DskipTests"]
            os: [windows]
    - image: message-service
      context: message-service
      docker:
        dockerfile: src/main/docker/Dockerfile.jvm
      hooks:
        before:
          - command: ["../mvnw", "package", "-pl", "message-service", "-am", "-DskipTests"]
            os: [darwin, linux]
          - command: [".\\mvnw.cmd", "package", "-pl", "message-service", "-am", "-DskipTests"]
            os: [windows]
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    # 1. Skaffold automatically installs the NGINX engine into the cluster
    - k8s/nginx-ingress-deploy.yml
    # 2. Skaffold applies your database, Java app, and the Ingress rules we just wrote
    - k8s/*.yaml
deploy:
  kubectl: { }
