quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=secretpassword

quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-service:5432/chatapp

quarkus.hibernate-orm.schema-management.strategy=update

identity-api/mp-rest/url=http://identity-service:80

quarkus.http.access-log.enabled=true
